name: BCV Scraper

on:
  schedule:
    # Corre todos los días hábiles (Lunes a Viernes) en UTC
    # 01:00 AM HLV -> 05:00 UTC
    - cron: '0 5 * * 1-5'
    # 05:00 AM HLV -> 09:00 UTC
    - cron: '0 9 * * 1-5'
    # 08:00 AM HLV -> 12:00 UTC
    - cron: '0 12 * * 1-5'
    # 05:30 PM HLV -> 21:30 UTC
    - cron: '30 21 * * 1-5'
  workflow_dispatch: # Permite ejecución manual

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python scraper.py
