name: BCV Scraper

on:
  schedule:
    # 05:00 AM HLV -> 09:00 UTC
    - cron: '0 9 * * 1-5'
    # 07:30 PM HLV -> 23:30 UTC
    - cron: '30 23 * * 1-5'
    # 05:00 PM HLV -> 21:00 UTC
    - cron: '0 21 * * 1-5'
    # 05:30 PM HLV -> 21:30 UTC
    - cron: '30 21 * * 1-5'
    # 06:00 PM HLV -> 22:00 UTC
    - cron: '0 22 * * 1-5'
    # 06:30 PM HLV -> 22:30 UTC
    - cron: '30 22 * * 1-5'
    # 07:00 PM HLV -> 23:00 UTC
    - cron: '0 23 * * 1-5'
  workflow_dispatch: # Permite ejecución manual

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python scraper.py
